### ISSUE TITLE
Moon positioning outside of Container

### ISSUE THREAD

**Issue by LondonJammo** [enoosoft/moon_phase#1]
The widget is lovely, well done.

The only problem, is the `size`, `resolution` and `scale` make no sense and are quite confusing to use. 

Can they be replaced with just a `width` and `height`, or even one parameter `boxSize` (as it will always be a square shape)?

To put the Widget into a Container size 100x100, the moon is painted off to one side outside the box, and I have to hack the values to move the moon into it.

Thanks

**Comment by enoosoft** [comment]
Actually, I know that widgets only work properly under certain conditions.
It's because of the Scale. A pure widget that only operates Height and
Width should be created another. So I maybe need some time. PR is also
welcome. Thank you for your reply.

2022년 2월 2일 (수) 02:28, James Paxton ***@***.***>님이 작성:

**Comment by enoosoft** [comment]
Scale parameter removed. Because it's too confusing. Now, You can adjust the scale only by size parameter. Please check it out.
